enum Actions {
  initializeContractAddress = 'initializeContractAddress',
  updateUserWalletData = 'updateUserWalletData',
  getFromLocalStorage = 'getFromLocalStorage',
  getLastSelectedUser = 'getLastSelectedUser',
  setToLocalStorage = 'setToLocalStorage',
  clearLocalStorage = 'clearLocalStorage',
  updateFromLocalStorage = 'updateFromLocalStorage',
  reqRefreshToken = 'reqRefreshToken',
  waitTokenExpiration = 'waitTokenExpiration',
  reqUserAuth = 'reqUserAuth',
  reqUserData = 'reqUserData',
  refreshUser = 'refreshUser',
  forceConnect = 'forceConnect',
  logout = 'logout',
  getBalance = 'getBalance',
  login = 'login',
  signup = 'signup',
  refreshTokens = 'refreshTokens',
  GetUser = 'GetUser',
  getFromLocalStorageUser = 'getFromLocalStorageUser',
  setToLocalStorageUser = 'setToLocalStorageUser',
}

export default Actions;
