const regionalCenters = [
  { text: 'Вінниця', value: 'Вінниця' },
  { text: 'Дніпро', value: 'Дніпро' },
  { text: 'Донецьк', value: 'Донецьк' },
  { text: 'Житомир', value: 'Житомир' },
  { text: 'Запоріжжя', value: 'Запоріжжя' },
  { text: 'Івано-Франківськ', value: 'Івано-Франківськ' },
  { text: 'Київ', value: 'Київ' },
  { text: 'Кропивницький', value: 'Кропивницький' },
  { text: 'Луганськ', value: 'Луганськ' },
  { text: 'Луцьк', value: 'Луцьк' },
  { text: 'Львів', value: 'Львів' },
  { text: 'Миколаїв', value: 'Миколаїв' },
  { text: 'Одеса', value: 'Одеса' },
  { text: 'Полтава', value: 'Полтава' },
  { text: 'Рівне', value: 'Рівне' },
  { text: 'Суми', value: 'Суми' },
  { text: 'Тернопіль', value: 'Тернопіль' },
  { text: 'Ужгород', value: 'Ужгород' },
  { text: 'Харків', value: 'Харків' },
  { text: 'Херсон', value: 'Херсон' },
  { text: 'Хмельницький', value: 'Хмельницький' },
  { text: 'Черкаси', value: 'Черкаси' },
  { text: 'Чернівці', value: 'Чернівці' },
  { text: 'Чернігів', value: 'Чернігів' },
];

export default regionalCenters;
